### PR TITLE
Initial pull request for multi-lingual support based on the gatsby-plugin-i18n

### LINKED ISSUE #43: Add multi-language support

### PR DESCRIPTION
**Pull request by felixfaassen**
This is a first initial commit for multi-lingual support based on the gatsby-plugin-i18n. As discussed with @bartjkdp . Before adding all the translations I would like you to review if this implementation is the correct one. For this purpose this PR does contain partial unfinished translations to test the implementation (partially translated: index.js, the Navigation component and roadmap.js)

Implemented using advice written in this blogpost:
https://www.gatsbyjs.com/blog/2020-02-19-how-to-build-multilingual-sites-with-gatsby/

Currently a lot of components of pages are imported therefore I need to statically import them for each language.  (would be nice if we could implement it to resolve automatically using the plugin however I have not find a way how to do it)

### Setup:
- you can access the translation by adding /en to the root of the site. (default language is NL, see gatsby=config.js for details.)
- pages can be translated by index.<ISO language code>.js. These are automatically routed to hostname/<ISO language code>/pagename
- pages which import other components are not automatically resolved as above and need be references explicit in the import (eg. import of the menu.json)

### TODO:
- Implement language switcher menu in navigation header
- finish translations (translations will be added if this implementation is correct)
- review the translations (will be done in a separate pull request)

In order to get in running you might need to seperately install the language plugin:
yarn add gatsby-plugin-i18n

More information on the used plugin can be found here:
https://github.com/angeloocana/gatsby-plugin-i18n

PS: If you want all the translations in this pull request please let me know in the review.

Closes #43

### CODE REVIEW

**Comment by felixfaassen** [comment]
test fails as plugin needs to be installed with yarn instead of npm

**Comment by felixfaassen** [comment]
Yesterday I had a call with @bartjkdp about this PR.  Summary of that call:

- Add the default.js template to be aware of different language versions by using a 'lang' frontmatter parameter
- Make barebones language selector
- Use react's language framework for translating site using key-val pairs used in page templates to minimize duplication of code.
- We will keep working on this branch before merging this PR

**Comment by bartjkdp** [comment]
Just pushed some changes:

- Menu items are now stored per language key in menu.json
- Added a very basic language toggle, some styling is still required
- Replace duplicate components with dynamic logic

**Comment by felixfaassen** [comment]
Here is the first English translation for the Signalen website. This is a big PR which includes the English translation made by @AlbaRoza as well as technical implementation changes done by @bartjkdp for menu and footer localization.

**Comment by Ainali** [comment]
Quick comment about different spellings, we have two instances of open-source, and two of open source.  We should go with one of them (and probably open source).

**Comment by Ainali** [comment]
We have a similar issue on 'Signalen' vs. 'Signals'. I guess the latter is a machine translated error and that we should go with Signalen everywhere, right?

**Review by bartjkdp — APPROVED** [review]

**Pull request merged**
