### PR TITLE
Community meetings

### LINKED ISSUE #60: Provide information about meeting schedule and links to meetings
We should provide information about the meeting schedules and links to meetings on the Signalen website to be more open and welcome contributions. Also, provide pointers so people can learn how they can join these calls.

### PR DESCRIPTION
**Pull request by felixfaassen**
Fixes #60

### CODE REVIEW

**Review by AlbaRoza — APPROVED** [review]
Ready to go!

**Review by AlbaRoza — COMMENTED** [review]
Nice catch of the typo!

**Comment by felixfaassen** [comment]
> Nice catch of the typo!

@AlbaRoza  thx. Could you also approve the PR (next to providing a comment everything is OK ;-) )

**Review by AlbaRoza — APPROVED** [review]
You're very right. Approved!

**Pull request merged**
